# Islandora Dev Settings to be used with $app['debug'] == TRUE
islandora:
  fedoraProtocol: http
  fedoraHost: "localhost:8080"
  fedoraPath: /fcrepo/rest
  tripleProtocol: http
  tripleHost: "localhost:8080"
  triplePath: /bigdata/sparql
  resourceIdRegex: "(?:[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?"
# This domain is used as namespace (hashed) when generating UUID V5 identifiers
  defaultNamespaceDomainUuuidV5: "www.islandora.ca"